spring:
  application:
    name: TMT-BE-MemberServer
  datasource:
    url: jdbc:mysql://localhost:3306/tmtsecurity
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: localhost
#    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.type: debug
    p6spy: info

springdoc:
  packages-to-scan: ScreeningHumanity.defaultserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

#Token
JWT:
  SECRET_KEY: sldkfjsoidfjwoeir12393012809vxcv89usdfkjn1203491iu0isdfl